package com.unlock.core

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * All user-facing strings in one place, in English and Russian, switched instantly at runtime
 * via [LocalStrings] (no app restart). Format strings use %d / %s with String.format at call sites.
 */
data class Strings(
    // common
    val appName: String,
    val refresh: String,
    val ok: String,
    val needsShizuku: String,
    // nav
    val navDashboard: String,
    val navApps: String,
    val navRunning: String,
    val navAutostart: String,
    val navHealth: String,
    val navSettings: String,
    // dashboard
    val performanceHealth: String,
    val analysing: String,
    val tBattery: String,
    val tPeakTemp: String,
    val tRam: String,
    val tStorage: String,
    val tPowerDraw: String,
    val freeSuffix: String,
    val sensorsSuffix: String,
    val inventory: String,
    val invUser: String,
    val invSystem: String,
    val invDisabled: String,
    val invAutostart: String,
    val manageApps: String,
    val fullPowerOff: String,
    val bannerNeedsPerm: String,
    val bannerNotRunning: String,
    val setUp: String,
    // apps
    val searchAppsFmt: String,
    val sort: String,
    val fAll: String,
    val fUser: String,
    val fSystem: String,
    val fDisabled: String,
    val fAutostart: String,
    val fSafeDebloat: String,
    val sortName: String,
    val sortSize: String,
    val sortLastUsed: String,
    val sortInstallDate: String,
    val tagCore: String,
    val tagDebloatSafe: String,
    val usedPrefix: String,
    val actSleep: String,
    val actDisable: String,
    val actUninstall: String,
    val actEnable: String,
    val actForceStop: String,
    val actClearData: String,
    val actRestore: String,
    val actAppInfo: String,
    val sheetVersion: String,
    val sheetType: String,
    val sheetSize: String,
    val sheetLastUsed: String,
    val sheetForeground: String,
    val sheetTargetSdk: String,
    val sheetInstaller: String,
    val typeSystem: String,
    val typeUser: String,
    val protectedSheetNote: String,
    // autostart
    val autostartTitleFmt: String,
    val connectShizukuAutostart: String,
    val autostartStopped: String,
    val autostartAllowedFmt: String,
    // running
    val liveProcessesFmt: String,
    val recentlyActive: String,
    val actStop: String,
    // diagnostics
    val systemDiagnostics: String,
    val performanceAntiThrottle: String,
    val antiThrottleDesc: String,
    val whySlow: String,
    val topDrainFmt: String,
    val topRamFmt: String,
    val thermals: String,
    val thermalStatusLabel: String,
    val headroom: String,
    val cpuTitleFmt: String,
    val clockCeilingFmt: String,
    val batteryPower: String,
    val dLevel: String,
    val dVoltage: String,
    val dHealth: String,
    val dSoh: String,
    val dCycles: String,
    val dCapacity: String,
    val dTemperature: String,
    val dCurrentNow: String,
    val dPower: String,
    val dChargeCounter: String,
    val dTechnology: String,
    val voltageNote: String,
    val memory: String,
    val usedLabel: String,
    val lowMemory: String,
    // settings
    val sShizukuTitle: String,
    val sShizukuConnectedFmt: String,
    val sShizukuNeedsPerm: String,
    val sShizukuNotConnected: String,
    val sGrantPermission: String,
    val sGrantExtra: String,
    val sShizukuHowto: String,
    val sOpenShizuku: String,
    val sUsageTitle: String,
    val sUsageGranted: String,
    val sUsageNotGranted: String,
    val sOpenSettings: String,
    val sRecheck: String,
    val sLanguage: String,
    val sRecentActions: String,
    val sClear: String,
    val sUndo: String,
    val sSafety: String,
    val sSafetyBody: String,
) {
    companion object {
        fun en() = Strings(
            appName = "Unlock",
            refresh = "Refresh",
            ok = "OK",
            needsShizuku = "Needs Shizuku",
            navDashboard = "Dashboard",
            navApps = "Apps",
            navRunning = "Running",
            navAutostart = "Autostart",
            navHealth = "Health",
            navSettings = "Settings",
            performanceHealth = "Performance health",
            analysing = "Analysing…",
            tBattery = "Battery",
            tPeakTemp = "Peak temp",
            tRam = "RAM",
            tStorage = "Storage",
            tPowerDraw = "Power draw",
            freeSuffix = "free",
            sensorsSuffix = "sensors",
            inventory = "Inventory",
            invUser = "User",
            invSystem = "System",
            invDisabled = "Disabled",
            invAutostart = "Autostart",
            manageApps = "Manage apps",
            fullPowerOff = "Full power is off",
            bannerNeedsPerm = "Shizuku is running — grant permission to control system apps.",
            bannerNotRunning = "Connect Shizuku (no root) to uninstall/disable/sleep system apps.",
            setUp = "Set up",
            searchAppsFmt = "Search %d apps",
            sort = "Sort",
            fAll = "All",
            fUser = "User",
            fSystem = "System",
            fDisabled = "Disabled",
            fAutostart = "Autostart",
            fSafeDebloat = "Safe debloat",
            sortName = "Name",
            sortSize = "Size",
            sortLastUsed = "Last used",
            sortInstallDate = "Install date",
            tagCore = "Core",
            tagDebloatSafe = "Debloat-safe",
            usedPrefix = "used",
            actSleep = "Sleep",
            actDisable = "Disable",
            actUninstall = "Uninstall",
            actEnable = "Enable",
            actForceStop = "Force stop",
            actClearData = "Clear data",
            actRestore = "Restore",
            actAppInfo = "App info",
            sheetVersion = "Version",
            sheetType = "Type",
            sheetSize = "Size",
            sheetLastUsed = "Last used",
            sheetForeground = "Foreground (30d)",
            sheetTargetSdk = "Target SDK",
            sheetInstaller = "Installer",
            typeSystem = "System",
            typeUser = "User",
            protectedSheetNote = "⛔ Protected core package — removing or disabling it can bootloop the phone or break payments / Secure Folder. Destructive actions are blocked.",
            autostartTitleFmt = "Apps that start themselves on boot (%d)",
            connectShizukuAutostart = "Connect Shizuku to control autostart. The toggle stops the whole app's autostart (works on Samsung); per-component disable isn't possible without root.",
            autostartStopped = "Autostart stopped",
            autostartAllowedFmt = "Autostart allowed · %d trigger(s)",
            liveProcessesFmt = "Live processes (%d)",
            recentlyActive = "Recently active (enable Shizuku for live processes)",
            actStop = "Stop",
            systemDiagnostics = "System diagnostics",
            performanceAntiThrottle = "Performance (anti-throttle)",
            antiThrottleDesc = "Disables Samsung GOS + low-power mode and pins fixed-performance. Kernel/HAL throttling on real heat still needs root, and some parts reset on reboot.",
            whySlow = "Why it might feel slow",
            topDrainFmt = "Top battery drain (estimated, %d)",
            topRamFmt = "Top RAM use (%d)",
            thermals = "Thermals",
            thermalStatusLabel = "Thermal status",
            headroom = "Headroom",
            cpuTitleFmt = "CPU (%d cores%s)",
            clockCeilingFmt = "Clock ceiling at %d%% of hardware max",
            batteryPower = "Battery & power",
            dLevel = "Level",
            dVoltage = "Voltage",
            dHealth = "Health",
            dSoh = "State of health",
            dCycles = "Charge cycles",
            dCapacity = "Capacity",
            dTemperature = "Temperature",
            dCurrentNow = "Current now",
            dPower = "Power",
            dChargeCounter = "Charge counter",
            dTechnology = "Technology",
            voltageNote = "Voltage above is the battery pack. The SoC/CPU-rail voltage and a full throttle override are not exposed without root. A low State of health is what makes the system cap sustained performance.",
            memory = "Memory",
            usedLabel = "Used",
            lowMemory = "System reports LOW MEMORY",
            sShizukuTitle = "Shizuku — full power without root",
            sShizukuConnectedFmt = "Connected ✓  (running as %s)",
            sShizukuNeedsPerm = "Shizuku is running — permission needed.",
            sShizukuNotConnected = "Not connected.",
            sGrantPermission = "Grant permission",
            sGrantExtra = "Grant Unlock extra privileges",
            sShizukuHowto = "How to start Shizuku (one-time, no root):\n1. Install Shizuku from GitHub / Play.\n2. Enable Developer options → Wireless debugging (Android 11+).\n3. In Shizuku, tap “Start” (pairing) — or start it from a PC over ADB.\n4. Come back here and grant permission.",
            sOpenShizuku = "Open Shizuku",
            sUsageTitle = "Usage access",
            sUsageGranted = "Granted ✓ — sizes, battery blame and last-used are available.",
            sUsageNotGranted = "Not granted — needed for app sizes and usage stats.",
            sOpenSettings = "Open settings",
            sRecheck = "Re-check",
            sLanguage = "Language",
            sRecentActions = "Recent actions",
            sClear = "Clear",
            sUndo = "Undo",
            sSafety = "Safety",
            sSafetyBody = "• Uninstall removes apps for the current user only (--user 0); most are restorable, and a factory reset brings system apps back.\n• Disable is fully reversible.\n• Don't remove core packages (SystemUI, phone, providers) — it can cause a bootloop.\n• Unlock never requires root and sends nothing off-device.",
        )

        fun ru() = Strings(
            appName = "Unlock",
            refresh = "Обновить",
            ok = "OK",
            needsShizuku = "Нужен Shizuku",
            navDashboard = "Обзор",
            navApps = "Приложения",
            navRunning = "Запущенные",
            navAutostart = "Автозапуск",
            navHealth = "Здоровье",
            navSettings = "Настройки",
            performanceHealth = "Состояние производительности",
            analysing = "Анализ…",
            tBattery = "Батарея",
            tPeakTemp = "Пик. темп.",
            tRam = "ОЗУ",
            tStorage = "Хранилище",
            tPowerDraw = "Потребление",
            freeSuffix = "свободно",
            sensorsSuffix = "датч.",
            inventory = "Инвентарь",
            invUser = "Свои",
            invSystem = "Системные",
            invDisabled = "Отключены",
            invAutostart = "Автозапуск",
            manageApps = "К приложениям",
            fullPowerOff = "Полный доступ выключен",
            bannerNeedsPerm = "Shizuku запущен — выдайте разрешение для управления системными приложениями.",
            bannerNotRunning = "Подключите Shizuku (без root), чтобы удалять/отключать/усыплять системные приложения.",
            setUp = "Настроить",
            searchAppsFmt = "Поиск среди %d приложений",
            sort = "Сортировка",
            fAll = "Все",
            fUser = "Свои",
            fSystem = "Системные",
            fDisabled = "Отключённые",
            fAutostart = "Автозапуск",
            fSafeDebloat = "Безопасно удалить",
            sortName = "Имя",
            sortSize = "Размер",
            sortLastUsed = "Использовано",
            sortInstallDate = "Дата установки",
            tagCore = "Ядро",
            tagDebloatSafe = "Удаляемо",
            usedPrefix = "исп.",
            actSleep = "Усыпить",
            actDisable = "Отключить",
            actUninstall = "Удалить",
            actEnable = "Включить",
            actForceStop = "Остановить",
            actClearData = "Очистить данные",
            actRestore = "Восстановить",
            actAppInfo = "О приложении",
            sheetVersion = "Версия",
            sheetType = "Тип",
            sheetSize = "Размер",
            sheetLastUsed = "Использовано",
            sheetForeground = "На экране (30д)",
            sheetTargetSdk = "Target SDK",
            sheetInstaller = "Установщик",
            typeSystem = "Системное",
            typeUser = "Пользовательское",
            protectedSheetNote = "⛔ Защищённый системный пакет — удаление/отключение может привести к bootloop или сломать платежи / Secure Folder. Опасные действия заблокированы.",
            autostartTitleFmt = "Приложения с автозапуском (%d)",
            connectShizukuAutostart = "Подключите Shizuku для управления автозапуском. Переключатель останавливает автозапуск всего приложения (работает на Samsung); отключение отдельных компонентов без root невозможно.",
            autostartStopped = "Автозапуск остановлен",
            autostartAllowedFmt = "Автозапуск разрешён · %d триггер(ов)",
            liveProcessesFmt = "Запущенные процессы (%d)",
            recentlyActive = "Недавно активные (включите Shizuku для реального списка)",
            actStop = "Стоп",
            systemDiagnostics = "Диагностика системы",
            performanceAntiThrottle = "Производительность (анти-троттлинг)",
            antiThrottleDesc = "Отключает Samsung GOS и энергосбережение, фиксирует производительность. Аппаратный/HAL троттлинг при реальном перегреве требует root, часть сбрасывается после перезагрузки.",
            whySlow = "Почему может тормозить",
            topDrainFmt = "Больше всего жрут батарею (оценка, %d)",
            topRamFmt = "Больше всего ОЗУ (%d)",
            thermals = "Температуры",
            thermalStatusLabel = "Тепловой статус",
            headroom = "Запас",
            cpuTitleFmt = "ЦП (%d ядер%s)",
            clockCeilingFmt = "Потолок частоты — %d%% от аппаратного максимума",
            batteryPower = "Батарея и питание",
            dLevel = "Уровень",
            dVoltage = "Напряжение",
            dHealth = "Здоровье",
            dSoh = "Состояние (SoH)",
            dCycles = "Циклы заряда",
            dCapacity = "Ёмкость",
            dTemperature = "Температура",
            dCurrentNow = "Ток сейчас",
            dPower = "Мощность",
            dChargeCounter = "Счётчик заряда",
            dTechnology = "Технология",
            voltageNote = "Напряжение выше — это напряжение аккумулятора. Напряжение на SoC/процессор и полный обход троттлинга без root недоступны. Именно низкое состояние батареи (SoH) заставляет систему ограничивать производительность.",
            memory = "Память",
            usedLabel = "Использовано",
            lowMemory = "Система сообщает о НЕХВАТКЕ ПАМЯТИ",
            sShizukuTitle = "Shizuku — полный доступ без root",
            sShizukuConnectedFmt = "Подключено ✓  (работает как %s)",
            sShizukuNeedsPerm = "Shizuku запущен — нужно разрешение.",
            sShizukuNotConnected = "Не подключено.",
            sGrantPermission = "Выдать разрешение",
            sGrantExtra = "Выдать Unlock доп. права",
            sShizukuHowto = "Как запустить Shizuku (один раз, без root):\n1. Установите Shizuku из GitHub / Play.\n2. Включите «Для разработчиков» → Беспроводная отладка (Android 11+).\n3. В Shizuku нажмите «Start» (сопряжение) — или запустите с ПК через ADB.\n4. Вернитесь сюда и выдайте разрешение.",
            sOpenShizuku = "Открыть Shizuku",
            sUsageTitle = "Доступ к статистике использования",
            sUsageGranted = "Выдан ✓ — доступны размеры, расход батареи и время использования.",
            sUsageNotGranted = "Не выдан — нужен для размеров и статистики приложений.",
            sOpenSettings = "Открыть настройки",
            sRecheck = "Проверить снова",
            sLanguage = "Язык",
            sRecentActions = "Недавние действия",
            sClear = "Очистить",
            sUndo = "Отменить",
            sSafety = "Безопасность",
            sSafetyBody = "• Удаление убирает приложение только для текущего пользователя (--user 0); большинство восстановимо, а сброс к заводским возвращает системные приложения.\n• Отключение полностью обратимо.\n• Не удаляйте ключевые пакеты (SystemUI, телефон, провайдеры) — это может вызвать bootloop.\n• Unlock не требует root и ничего не отправляет с устройства.",
        )
    }
}

val LocalStrings = staticCompositionLocalOf { Strings.en() }
